---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 787733398999666688-373IMirSv1JOeWv6JUDDB05Y21qW5cC
:access_token_secret: Bh2JQPErY5jT1GYCHcEwNseiotssZXbaLVZq14tw0zrUH
